custommem="/usr/bin/free -m"
custombw="/usr/bin/bwm-ng -o plain -c 1 -t 5000"
customdstat="/usr/bin/dstat --noupdate -a 1 5"
customa2ctl="/usr/local/apache/bin/apachectl fullstatus"
custommysqladmin="/usr/bin/mysqladmin processlist"
customsar="/usr/bin/sar -q"
customtop="/usr/bin/top -b -n 1 -c"
customproc="/bin/ps axuf"